remote_theme: vsanthanam/gh-proj-theme
# show_downloads: true
name: WeakReference

project:
    version: 0.0.3
    download_url: https://www.github.com/vsanthanam/WeakReference/releases

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: Documentation
        url: https://weak.tools/docc/documentation/weakreference
      - title: GitHub
        url: https://www.github.com/vsanthanam/WeakReference
    footer:
      - title: GitHub
        url: https://www.github.com/vsanthanam/WeakReference
      - title: Issues
        url: https://www.github.com/vsanthanam/WeakReference/issues?state=open
      - title: About Me
        url: https://www.vsanthanam.com

ui:
    header:
        color1: "#80D0C7"
        color2: "#13547A"
        trianglify: true

social:
    github:
        user: vsanthanam
        repo: WeakReference
    twitter:
        enabled: false
        via:
        hash:
        account: 
    facebook:
        enabled: false
        profileUrl:

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
